---
mysql-01.demo.io:
  mysql:
    check_state: 0
    check_output: "MySQL is up and running"
    acknowledgement: false
    downtime: false
  mysql-backup:
    check_state: 2
    check_output: "backup job is running"
    acknowledgement: true
    downtime: true


