// Code generated by "esc -o static.go -pkg annotate -prefix static static"; DO NOT EDIT.

package annotate

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/index.html": {
		local:   "static/index.html",
		size:    2922,
		modtime: 1514987523,
		compressed: `
H4sIAAAAAAAC/5xWb2/jxBN+nXyK/e1PObXS2e5xSEBrG5WjvKMtUF4ghKqJPbHnut71eSfpRYjvjtZ/
GtuxS+BNYu8+88zszDzjDf/3/d2Hh9/ub0TOhYqXofsTCnQWSdTSLSCk8VIIIcICGUSSQ2WRI/nrww/e
17K/paHASO4In0tTsRSJ0YyaI/lMKedRijtK0Ktf3grSxATKswkojN75Fx0VEyuMv7v/8e5WXGttGBjD
oFltEIr0k6hQRZISo6XIK9xEEqxFtsEGdm7Vp8RIwfsSI0kFZBh89mp0n6MxzJlLexkEG6PZ+pkxmUIo
yfqJKYLE2m83UJDaRz+btWFz+eXFxduvLi5kE4HlvUKbI7I8iq6310bC+Jkd5SjmxBSF0b7b+A8kNaI1
DoOmXuHapPt4Gaa0E4kCayPpqgGksep89Packds4XvNIH0ymzTyLCZPRQuGGe8gxWpnMjLaPIMcMLzAq
shYmaiqPikwKWyUvaVyXLoulzqQAxZEc9tAcry1Bd/7XkGYoBaUuXVvNMvZ9PwwcZCLwIKXd9HlecRW/
0WtbXonr29u7h+uHm3/BPloav84XpqIsn65Mo1BMiWGtXG9VW5QdC+lyy6L+9doOqVPzaUvJ0yM0eSWn
wBQYvFJBgrlRKVaR/MlhutyT0b4v4/n4m8d24dCdzpmjnmk/ZSAlV22H614GPWzLtn0HDnrOO5ehTSoq
ua8wNwkbatyh5kcuSjUhnRI0trhwFVG6imW8XCyOIF6b695ZBiDSGyNqT6/paWDCVKBlKMqJ1l6Eq+hl
fzUmGRbi+L3vBDJ7SlwrsTGVONtBJRgyQVrwufhTrOLlYk7tDFlLM4SsIoZsFYfruH7+nSH7YxWHwboX
4oxEXBx/DZz2QItxAMNjrbfMRtsjtSwOY8LoRFHy1Eqgmyxnb/7//purtvr18/mLhhpSUeNlPFAFTkl/
MXJkc/N8kxKb6p+9yHjMfFIWDkL2sPY06Oaezh+77fqLE8mUbKlgfym00Xh1lLHXXHhsxl27OHEq9bia
AVVhtlUwG/XUdLqvzI5SFAeUcJoXOVboT4yqKZUcKeX4kGvDbIpJdQ6rnFOKp1a566UPoBNUc5+PsQc4
uVdl/AvqdLo35+dG97x4GazNRO3N1v6n+uOnLVZ7773/hf/OL0j7H61LemczZeKuZ/CM1hTogVInWDAW
pQImnZ0Abu9grwALmIszdpfZs/Or/qGD9gYWNBfr5d8BAAD//0EatidqCwAA
`,
	},

	"/main.js": {
		local:   "static/main.js",
		size:    2948,
		modtime: 1514986760,
		compressed: `
H4sIAAAAAAAC/+xWXW/bNhR996+4YAyYml3a2bA9OFWGYulDh6LplvRpGAJWvLa5yJeaSNnxWv/34VKW
JzvykA1DgAHViyXej3NInXvkWUVZsI4gd9q8XiEFLxP41AMA6Ks5hh9vrt9JMdaFHa/Oxx+LMcYkAUNY
WzJurXKXaW6hPOoyW4yg6SmNDrppxtfCGrwpLBGWMrnYL9sZxFRIU5jA58+we0iBqjw/WKjI4MwSmnbb
yFWKl8auIMu19+mAXLAzW/OCQhPmg8t3DirSRC7ogAbqfcDMVWSUUi/Hxq4uRaKYpEyULgokc+ukOGN0
kaiZNviGJP9YatHfwZ9lrqLADcIyl2IiWilbwNzjEeWVLiHWQAqTw3YzV4Lk+D1uwBIcH2RzxfLh8OJR
gGtropCCrFEu4ZsEvofvJhOYwvm3E/iqru+udgWfnYe0A5YvozdTEFQtsbSZGMEGdXmwsHQUFlMQfuHK
IEZParJwFTf5+oWxcxu4iaUq4MGSx8yRaS096rzt3pHRASEFwjVc6YBRcr/c4+ZXFewSk9NFN6G0NIcU
4pMK7q3LdI63drkLSWHwRbYQo+bUkoteZ7eoOT5Sa6bwF741I2AOPuhlMW1hjiC084Ke+xObixqHFMKy
yKWIOHd8L0Y1aBejvoxV/1Ly278fgPjQHoF4t00uetteb+86v1c2u3+1m0lp92PNW1qi93rOr6wvB2cx
8243vtbRIFEBH0LjI+whuwKVI80XYe8m+z4pCHG00Okn0Tw2UvzEkPBqDwm3+BAgOIiSVko1I/5ovPtK
/6Yf5OHkhE3BSn5/fXN7NA5VmU/hsceO2WStOczlNzNttnAY8lWWoffTIwP+1CmYqsx3w/Dh57fy2MoX
Jc5OTsSGXaEq853hv9elXnr+VkjBQdFRyF+XH1gRkjM6EvgVD4bW1Jq7roI8n0xOKm7bHPyBmPRTdMQg
w8HzCumLhP4vEvILt35tbHClrG2zpSNrIAVxJoYxMhQtDd1hrBF1yz4LUBW6RAoyUTNLRgr1sQrBkRdd
9OoKn1uDV25N8sgl2Z+fhdUb6ib1oeigZJD+I1KZ91IY64tcb8QIBDlCcQRYIgvgSgct20hP1uA/0h0n
e/sHnkzmYJPc+ufMyyPY6bPN3pINe97trXDanwEAAP//R4mb3IQLAAA=
`,
	},

	"/style.css": {
		local:   "static/style.css",
		size:    1091,
		modtime: 1514985026,
		compressed: `
H4sIAAAAAAAC/4xS7W7bMAz8n6cgMAzYgjm1M3RtlKehLNoWqpKaTC/phr37UH9kjmcD08+jyDse7+C5
ki9wUKxb+LUDAJAflKogFwONd4743KMRnfNcZ8nXjRoo8ni9L6hEA8VxCVtRldep8nu36xlHqot32hgo
nvKpaDtV4fa+fnxc1A/fO1++jJ8sli91ko5dVkqQZOCDs/j49Dx0ILMoqhfOyHmVNLaVgTAZsKLNoLgK
gmogUKUrmx1vC0+i8/zjAChdNcPgazZQEiulAX/YW0mOkoEiXqGV4B3Y0NF5/7Cu7J1p4cyN5E7uevdg
9X8NmO3bH/TfRWbwig8LAZ5jpyNxQ0NCjsuEDKGZRWRwJ0vofNca+Dbhcxl/r3FpvFLWRizJAMslYTxv
5HVVnZ0O73wbA74ZFqaNv/vFV8/Bv39e6phkrA05JKq7gGk7pVi5osSN7nnCx1t+zW+Wrkyr+rc+zdBr
1DdjqZJEU/7HvtPpNOZBWLPW/yQDz7fQCCuxGkDV9MmhYhYDltRIcJQ+92x/AgAA//998gv9QwQAAA==
`,
	},

	"/": {
		isDir: true,
		local: "static",
	},
}
