{
 "title": "Business Processes",
 "tags": [ "Business Process" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bp",
    "label": "BP",
    "query": "SHOW TAG VALUES WITH KEY = \"BP\""
   },
   {
    "name": "kpi",
    "label": "KPI",
    "query": "SHOW TAG VALUES WITH KEY = \"KPI\""
   },
   {
    "name": "svc",
    "label": "SVC",
    "query": "SHOW TAG VALUES WITH KEY = \"SVC\" WHERE \"BP\" =~ /^$bp$/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BP Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_BP",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "BP" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BP",
     "query": "SELECT max(\"status\") FROM \"BP\" WHERE \"BP\" =~ /^$bp$/ AND $timeFilter GROUP BY time($interval), \"BP\" fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "BP", "operator": "=~", "value": "/^$bp$/" }
     ]
    }
   ]
  },
  {
   "title": "KPI Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_KPI",
     "groupBy": [
      { "params": [ "KPI" ], "type": "tag" }
     ],
     "measurement": "KPI",
     "query": "SELECT max(\"value\") FROM \"BP\" WHERE \"BP\" =~ /^$bp$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BP", "operator": "=~", "value": "/^$bp$/" },
      { "condition": "AND", "key": "KPI", "operator": "=~", "value": "/^$kpi$/" }
     ]
    }
   ]
  },
  {
   "title": "SVC Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_SVC",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "SVC" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SVC",
     "query": "SELECT max(\"status\") FROM \"autogen\".\"SVC\" WHERE status != 2 AND \"BP\" =~ /^$bp$/ AND \"KPI\" =~ /^$kpi$/ AND \"SVC\" =~ /^$svc$/ AND $timeFilter GROUP BY time($__interval), \"SVC\" fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "BP", "operator": "=~", "value": "/^$bp$/" },
      { "condition": "AND", "key": "KPI", "operator": "=~", "value": "/^$kpi$/" },
      { "condition": "AND", "key": "SVC", "operator": "=~", "value": "/^$svc$/" }
     ]
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Availability (Time Range)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "$tag_BP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - (sum(\"status\") / count(\"status\")) AS Availability FROM \"BP\" WHERE \"BP\" =~ /^$bp$/ AND $timeFilter AND \"status\" < 2 GROUP BY \"BP\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}